server:
  port: 8082

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  swagger:
    api-base-package: com.zhy.controller
    enable-security: true
    title: spring-security-mybatis-rbac-app
    description: 基于Swagger3在线文档
    version: v1.0.0
#    contact-name: 于状状
    contact-url: https://github.com/ojinx
#    contact-email: sshl0323@gmail.com
  security:
    jwt:
      secret: JWTSECRET
      expiration: 3600 # jwt有效期（秒）
    captcha:
      expiration: 60 # 验证码有效期（秒）
    auth:
      expiration: 3600 # 用户信息缓存1小时
    permit-all:
      urls:
        - /swagger-ui.html
        - /swagger-ui/
        - /swagger-resources/**
        - /swagger/**
        - /**/v2/api-docs #swagger2
        - /**/v3/api-docs #swagger3 openapi
        - /**/*.js
        - /**/*.css
        - /**/*.png
        - /**/*.icon
        - /webjars/springfox-swagger-ui/**
        - /actuator/**
        - /druid/**
        - /api/auth/signin
        - /api/auth/signup
        - /api/captcha/generate
        - /api/captcha/verify
